### ISSUE TITLE
A happy path for installation on Linux

### ISSUE THREAD

**Issue by Dabbrivia** [madx/git-identity#14]
I have to install git-identity on many boxes because it is just too useful!! :-) 
To avoid figuring/typing the right commands here is the one-liner I have written: 

```
cd ~ && git clone https://github.com/madx/git-identity.git && sudo ln -
s ~/git-identity/git-identity /usr/local/bin/git-identity && sudo chmod ugo+x !$
```

You might consider adding this to the README.md as the happy path for installation on Linux. 
Creating this as an Issue instead of a pull request because it might be worth discussing/correcting first.

**Comment by somini** [comment]
It's a bit overkill to use sudo for this. You can link it to `$HOME/.local/bin` (`mkdir -p` that if it doesn't exist), since that's likely to be on the `$PATH` already.

The nicer option is to integrate this on your distro's repositories. With #9, this is unblocked now.

**Comment by somini** [comment]
https://aur.archlinux.org/packages/git-identity/

This is now on AUR, if you use Arch Linux.

**Comment by madx** [comment]
Thanks for your submission @Dabbrivia , I also agree with @Dabbrivia that this is a bit overkill to use sudo for this. I'll think about adding such a section to the README
