### ISSUE TITLE
Non-zero exit code when setting the identity

### ISSUE THREAD

**Issue by jceb** [madx/git-identity#19]
Thank you for the awesome tool. I noticed that when I set the identity with `git identity myidentity` that the exit code is `5` and not `0` as expected for a successful operation.

This problem is triggered by https://github.com/madx/git-identity/blob/master/git-identity#L162 which seems to be run regardless of whether it's specified in the local git configuration. Maybe add `|| true` to avoid failure or better test if the value is there before unsetting it?

**Comment by somini** [comment]
What's your `git` version? I think I had some of these errors in a past version, but it was fixed a while back.

**Comment by madx** [comment]
There we go! I just added `|| true` as you suggested
