### ISSUE TITLE
Tag a release for this project

### ISSUE THREAD

**Issue by somini** [madx/git-identity#9]
This is so useful I got tired of installing it manually and created a AUR package:

https://aur.archlinux.org/packages/git-identity-git/

After solving #8 (the only outstanding issue), can you please tag a v1.0 (as an example), so that I can create a non-development package.

**Comment by madx** [comment]
@somini Thanks for creating the package! I just tagged v1.0.0 so you might want to use this :)

**Comment by somini** [comment]
This is now done:

https://aur.archlinux.org/packages/git-identity/

Sorry for the months-long delay. :)

**Comment by madx** [comment]
No need to apologize given how long it took me as well lol 😂
Thanks a lot, I'll try to remember to add it to the readme!
